"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['timermac.pyw']
DATA_FILES = ['timericon.icns']
OPTIONS = {'iconfile': '/Users/groeneveld/Documents/Coding/Python/timer/timericon.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
